name: Deploy

on:
  push:
    branches:
      - master # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest # machine on which we want to run the code

    steps:
    - name: Checkout code # means to clone the code
      uses: actions/checkout@v2 

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        ssh -t -i keyfile ubuntu@ec2-16-16-198-27.eu-north-1.compute.amazonaws.com "sudo bash ~/deploy.sh"


